### DISCUSSION TITLE
Database class save and read issues

### DISCUSSION THREAD

**Discussion by pavlis** [mspass-team/mspass#136] [Design & Development]
Working on the getting started tutorial caused me to quickly recognize two problems we need to deal with.

1.  In this tutorial I have the user download data from IRIS with obspy's web service function and immediately save the results to wf_TimeSeries.  Works really slick because it avoids the giant seed files like those we are dealing with for the usarray data.   Shows clearly, however, once again why right now the just in time model for data storage is not workable as it takes a solid 30 minutes to download just 3 usarray event files smaller than those I downloaded before.  What came up was that what we should want to show, which is this block of code:
```
strm=client.get_waveforms(
            starttime=UTCDateTime(stime),
            endtime=UTCDateTime(etime),
            network='TA',
            channel='BH?',
            location='*'
        )
        for d in strm:
            d_mspass=Trace2TimeSeries(d)
            print('Saving data for sta=',d_mspass['sta'],' and chan=',d_mspass['chan'])
            db.save_data(d_mspass)
```
runs fine but produces useless wf_TimeSeries entries.   A typical document saved that way from the draft tutorial looks like this:
```
{'_id': ObjectId('601993a7e4c0ed39f9898a26'),
 'calib': 1.0,
 'delta': 0.025,
 'npts': 59081,
 'sampling_rate': 40.0,
 'starttime': 1299825273.0,
 'time_standard': 'UTC',
 'gridfs_id': ObjectId('601993a7e4c0ed39f9898a27'),
 'storage_mode': 'gridfs'}
```
The data there are useless because there is nothing to link them to anything in site, channel, or source.  Source is a different issue that was a mistake in my script, but the issue is channel data.   The problem is the save_data function defaults to *include_undefined=False*.  As a result the net, sta, chan, and loc attributes are dropped in the save.   To fix this we need to do one of two things: (1) add net, sta, chan, and loc to the wf_TimeSeries schema as optional parameters, or (2) make the default for include_undefined True.  I would argue actually that we should do both.  The biggest user base for MsPASS will be people getting data from IRIS and not carrying net, sta, chan, and loc along like this will cause endless emails of complaints if left that way.  I actually think defaulting to include_undefined should default to true for the same reason.  Better to save junk than to lose critical data by mistake, especially since pymongo is pretty promiscuous on type.  
2. I think it would be a good convenience to the user to have *read_data* accept either an ObjectId or a doc from which would extract the ObjectId.  The difference is  only 2 or 3 lines of code.  For a beginner that is one less concept to have to grasp.   The counter argument is allowing a parameter to specify two drastically different data types is bad form and potentially causes more confusion than it fixes. 

In summary, some change for item 1 is essential.  Item 2 is a topic for discussion on which I am not as sure.

**Comment by pavlis** [comment]
I may have put the blame in the wrong place.  The wf_TimeSeries schema, I think, should have net, sta, chan, and loc added, BUT there adding *include_undefined=True" did not fix the problem.  It appears our Trace2TimeSeries converter is not working right as it should have transferred those attributes to the TimeSeries it creates.  I'm going to have to do some debugging here. 

This issue does not really change the need for a discussion of the two points above.

**Reply by pavlis** [reply]
That guess was wrong.  There was nothing wrong with Trace2TimeSeries.  The problem is in the save_data method and how it interacts with the schema class.   Debugging this showed this is the problem:
1.  Within *save_data* is this line:
```
if isinstance(mspass_object, TimeSeries):
     update_metadata_def = schema.TimeSeries
```
2.  That is used while looping over Metadata keys here:
```
for k in copied_metadata:
                if k in exclude_keys:
                    continue
                if update_metadata_def.is_defined(k):
                    if update_metadata_def.readonly(k):
                        continue
                    if not isinstance(copied_metadata[k], update_metadata_def.type(k)):
                        try:
                            # The following convert the actual value in a dict to a required type.
                            # This is because the return of type() is the class reference.
                            insert_dict[k] = update_metadata_def.type(
                                k)(copied_metadata[k])
                        except Exception as err:
                            raise MsPASSError('Failure attempting to convert key {} from {} to {}'.format(
                                k, copied_metadata[k], update_metadata_def.type(k)), 'Fatal') from err
                    else:
                        insert_dict[k] = copied_metadata[k]
```
This creates the problem because in the Metadata schema net, sta, chan, and loc are tagged as "readonly: True".   

What I don't understand here is why the Metadata schema is overlaid on that for TimeSeries. TimeSeries does not even define net, sta, chan, and loc so seems to me they should be undefined there.   

Something is definitely wrong and I'm not sure how to fix it.  

Here is a script you can run that should allow you to completely duplicate this problem:
```
from mspasspy.db.database import Database
from mspasspy.db.client import Client as DBClient
dbclient=DBClient()
db=Database(dbclient,'test')
from obspy import UTCDateTime
from mspasspy.util.converter import Trace2TimeSeries

# We have to redefine the client from obspy to use their so called bulk downloader
from obspy.clients.fdsn import RoutingClient
client = RoutingClient("iris-federator")

t0=UTCDateTime('2011-03-11T05:46:24.0')
origin_time=t0.timestamp
start_offset=763.0-60.0
end_offset=1400.0+2*60.0
stime=origin_time+start_offset
etime=origin_time+end_offset

strm=client.get_waveforms(
            starttime=UTCDateTime(stime),
            endtime=UTCDateTime(etime),
            network='TA',
            channel='BHZ',
            location='*'
        )
ens=list()
for tr in strm:
    d=Trace2TimeSeries(tr)
    ens.append(d)
print('number converted=',len(ens))
db.save_data(ens[0],include_undefined=True)
```
You can see what happens only by using this with a debugger and stepping through save_data

**Comment by wangyinz** [comment]
yeah, I was looking at it, too, and found the same problem. The reason Metadata schema is used here is that we are saving a data object, so we need to look at its metadata to know what is defined and how they should be saved.

The problem here is the disconnection in handling readonly. Those site/channel information are readonly because in Metadata definition, they belong to the site or channel collection. Thus, shouldn't be updated because those collections should never change or at least not in a wf update. Such behavior is meaningless right now because the `save_data` method does not support updating other collections than the targeting wf one anyway. I guess the question is, what shall we do with keys that belong to a different collection. Maybe we should change that section of code into something like this:
```python
                if k in exclude_keys:
                    continue
                if update_metadata_def.is_defined(k) and update_metadata_def.writeable(k):
                    if not isinstance(copied_metadata[k], update_metadata_def.type(k)):
                        try:
                            # The following convert the actual value in a dict to a required type.
                            # This is because the return of type() is the class reference.
                            insert_dict[k] = update_metadata_def.type(
                                k)(copied_metadata[k])
                        except Exception as err:
                            raise MsPASSError('Failure attempting to convert key {} from {} to {}'.format(
                                k, copied_metadata[k], update_metadata_def.type(k)), 'Fatal') from err
                    else:
                        insert_dict[k] = copied_metadata[k]
                elif include_undefined:
                    insert_dict[k] = copied_metadata[k]
```

**Reply by wangyinz** [reply]
Well, actually that's still not right... we don't want to override `readonly` with the `include_undefined` argument.

**Reply by wangyinz** [reply]
Well, actually we encountered the problem here mostly because the `mspass.yaml` defines a normalized schema, but here in this example, you really want to use an embedded schema. Maybe the solution is to just use a different schema file.

**Reply by wangyinz** [reply]
Probably a schema like this should work:
```yaml
Database:
  wf_TimeSeries:
    default: wf
    data_type: TimeSeries
    schema: 
      chan:
        type: string
        concept: channel name (e.g. HHZ, BHE, etc.) - normally a SEED channel code
        aliases: [channel, KCMPNM, channel.chan, wfdisc.chan]
      <<: &wf_TimeSeries
        _id:
          type: ObjectID
          concept: ObjectId used to define a data object
        npts:
          type: int
          concept: Number of data samples
          aliases: [nsamp, wfdisc.nsamp]
        delta:
          type: double
          concept: Data sample interval in seconds
          aliases: [dt]
        sampling_rate:
          type: double
          concept: Data sampling frequency in Hz=1/s
          optional: true
        starttime:
          type: double
          concept: Time of first sample of data (epoch time or relative to some other time mark)
          aliases: [t0, time]
        starttime_shift:
          type: double
          concept:  Time shift applied to define relative time of 0.0
          aliases:  t0shift
        utc_convertible:
          type:  bool
          concept:  When true starttime_shift can be used to convert relative time to UTC.
        time_standard:
          type: string
          concept: Defines time standard for meaning of t0 (default should be UTC)
        calib:
          type: double
          concept: Nominal conversion factor for changing sample data to ground motion units.
        storage_mode:
          type: string
          concept: The storage mode of the saved data ('file', 'url' or 'gridfs')
        dir:
          type: string
          concept: Directory path to an external file (always used with dfile)
          aliases: [file.dir, wfdisc.dir, wfprocess.dir]
          optional: true
        dfile:
          type: string
          concept: External data file name.
          aliases: [file.dfile, wfdisc.dfile, wfprocess.dfile]
          optional: true
        foff:
          type: int
          concept: Offset in bytes from beginning of a file to first data sample.
          aliases: [file.foff, wfdisc.foff, wfprocess.foff]
          optional: true
        url:
          type: string
          concept: Url to external data file.
          optional: true
        net:
          type: string
          concept: network code (net component of SEED net:sta:chan)
          aliases: [network, site.net, channel.net, wfdisc.net, site_net]
        sta:
          type: string
          concept: station code assigned to a spot on Earth (sta component of SEED net:sta:chan)
          aliases: [station, site.sta, channel.sta, wfdisc.sta, KSTNM]
        loc:
          type: string
          concept: location code assigned to an instrument (loc component of SEED net:sta:chan)
          aliases: [location, site.loc, channel.loc]
          optional: true
        gridfs_id:
          type: ObjectID
          concept: The _id of data file in the fs.files collection.
          optional: true
        history_object_id:
          reference: history_object
          optional: true
        elog_id:
          type: list
          reference: elog
          optional: true

  wf_Seismogram:
    data_type: Seismogram
    schema:
      <<: *wf_TimeSeries
      tmatrix:
        type: list
        concept: Three-component data's transformation matrix
  
  history_object:
    schema:
      _id:
        type: string
        concept: UUID used to define an unique entry in history collection.
      nodedata:
        type: bytes
        concept: serialized content of ProcessingHistory.

  elog:
    schema:
      _id:
        type: ObjectID
        concept: ObjectID used to define an unique entry in elog collection.
      logdata:
        type: list
        concept: a list of LogData.
      wf_Seismogram_id:
        reference: wf_Seismogram
        optional: true
      wf_TimeSeries_id:
        reference: wf_TimeSeries
        optional: true
      gravestone:
        type: dict
        concept: a copy of the Metadata of a dead object.
        optional: true


Metadata:
  TimeSeries:
    schema:
      _id:
        collection: wf_TimeSeries
        readonly: true
      npts:
        collection: wf_TimeSeries
        readonly: false
      delta:
        collection: wf_TimeSeries
        readonly: false
      sampling_rate:
        collection: wf_TimeSeries
        readonly: false
      starttime:
        collection: wf_TimeSeries
        readonly: false
      time_standard:
        collection: wf_TimeSeries
        readonly: false
      calib:
        collection: wf_TimeSeries
        readonly: false
      net:
        collection: wf_TimeSeries
        readonly: false
      sta:
        collection: wf_TimeSeries
        readonly: false
      loc:
        collection: wf_TimeSeries
        readonly: false
      chan:
        collection: wf_TimeSeries
        readonly: false
      
  Seismogram:
    schema:
      _id:
        collection: wf_Seismogram
        readonly: true
      npts:
        collection: wf_Seismogram
        readonly: false
      delta:
        collection: wf_Seismogram
        readonly: false
      sampling_rate:
        collection: wf_Seismogram
        readonly: false
      starttime:
        collection: wf_Seismogram
        readonly: false
      time_standard:
        collection: wf_Seismogram
        readonly: false
      calib:
        collection: wf_Seismogram
        readonly: false
      tmatrix:
        collection: wf_Seismogram
        readonly: false
      net:
        collection: wf_Seismogram
        readonly: false
      sta:
        collection: wf_Seismogram
        readonly: false
      loc:
        collection: wf_Seismogram
        readonly: false 
```
